
/* This file was automatically generated by pclu.*/

#include "pclu_err.h"
#include "pclu_sys.h"


extern errcode logit();
extern errcode file_nameOPcreate();
extern errcode gc_dump();
extern errcode stringOPconcat();
extern errcode intOPunparse();
extern errcode gc_read();
extern errcode stringOPc2s();
extern errcode charOPc2i();
extern errcode arrayOPaddh();
extern errcode arrayOPelements();
extern struct REQS *gc_dump_of_t_reqs;
extern struct OPS *int_ops;
extern OWN_req gc_dump_ownreqs;
struct OPS *gc_dump_of_int_table;
struct OPS *gc_dump_of_int_ops;
struct OPS *gc_dump_of_int_ops;
OWNPTR gc_dump_of_int_owns;
extern struct REQS *gc_read_of_t_reqs;
extern OWN_req gc_read_ownreqs;
struct OPS *gc_read_of_int_table;
struct OPS *gc_read_of_int_ops;
struct OPS *gc_read_of_int_ops;
OWNPTR gc_read_of_int_owns;
extern struct OPS *char_ops;
struct OPS *gc_dump_of_char_table;
struct OPS *gc_dump_of_char_ops;
struct OPS *gc_dump_of_char_ops;
OWNPTR gc_dump_of_char_owns;
struct OPS *gc_read_of_char_table;
struct OPS *gc_read_of_char_ops;
struct OPS *gc_read_of_char_ops;
OWNPTR gc_read_of_char_owns;
extern struct OPS *string_ops;
struct OPS *gc_dump_of_string_table;
struct OPS *gc_dump_of_string_ops;
struct OPS *gc_dump_of_string_ops;
OWNPTR gc_dump_of_string_owns;
struct OPS *gc_read_of_string_table;
struct OPS *gc_read_of_string_ops;
struct OPS *gc_read_of_string_ops;
OWNPTR gc_read_of_string_owns;
extern struct REQS *array_of_t_reqs;
extern OWN_req array_ownreqs;
extern struct OPS *array_ops;
struct OPS *array_of_int_table;
struct OPS *array_of_int_ops;
struct OPS *array_of_int_ops;
OWNPTR array_of_int_owns;
extern struct OPS *array_of_int_ops;
struct OPS *gc_dump_of_array_of_int_table;
struct OPS *gc_dump_of_array_of_int_ops;
struct OPS *gc_dump_of_array_of_int_ops;
OWNPTR gc_dump_of_array_of_int_owns;
struct OPS *gc_read_of_array_of_int_table;
struct OPS *gc_read_of_array_of_int_ops;
struct OPS *gc_read_of_array_of_int_ops;
OWNPTR gc_read_of_array_of_int_owns;
struct OPS *array_of_string_table;
struct OPS *array_of_string_ops;
struct OPS *array_of_string_ops;
OWNPTR array_of_string_owns;
extern struct OPS *array_of_string_ops;
struct OPS *gc_dump_of_array_of_string_table;
struct OPS *gc_dump_of_array_of_string_ops;
struct OPS *gc_dump_of_array_of_string_ops;
OWNPTR gc_dump_of_array_of_string_owns;
struct OPS *gc_read_of_array_of_string_table;
struct OPS *gc_read_of_array_of_string_ops;
struct OPS *gc_read_of_array_of_string_ops;
OWNPTR gc_read_of_array_of_string_owns;
CLUREF STR_;
CLUREF STR_INTEGER_040_050expected_040result_0405_051;
CLUREF STR__057tmp_057;
CLUREF STR_testint;
CLUREF STR_lib;
CLUREF STR_Result_072_040;
CLUREF STR_gc_137read_040signals_040not_137possible_072_040;
CLUREF STR_CHAR_040_050expected_040result_040_047_100_047_051;
CLUREF STR_testchar;
CLUREF STR_Result_072_040_047;
CLUREF STR__047_054_040;
CLUREF STR_STRING_040_050expected_040result_040_047abc_047_051;
CLUREF STR_teststring1;
CLUREF STR_abc;
CLUREF STR__047;
CLUREF STR_STRING_040_050expected_040result_040_047abcdefghij_047_051;
CLUREF STR_teststring2;
CLUREF STR_abcdefghij;
CLUREF STR_ARRAY_133INT_135_040_050expected_040result_0400_054_0401_054_0402_054_0403_054_0405_051;
CLUREF STR_testarrayofints;
CLUREF STR_Result;
CLUREF STR_ARRAY_133STRING_135_040_050expecting_040to_040get_040asdf0_054_040asdf1;
CLUREF STR_testarrayofstrings;
CLUREF STR_asdf0;
CLUREF STR_asdf1;
static int start_up_own_init = 0;

/**** BEGIN PROCEDURE start_up ****/

errcode start_up()
    {
    errcode err;
    errcode ecode2;
    CLUREF fn;
    CLUREF j;
    CLUREF why;
    CLUREF c;
    CLUREF c2;
    CLUREF s;
    CLUREF ai;
    CLUREF aix;
    CLUREF i1;
    CLUREF a;
    CLUREF ax;
    CLUREF s1;
        if (start_up_own_init == 0) {
        add_parm_info_type(0, int_ops, gc_dump_of_t_reqs);
        find_prociter_instance(gc_dump, 1, &gc_dump_ownreqs, &(gc_dump_of_int_ops));
        add_parm_info_type(0, int_ops, gc_read_of_t_reqs);
        find_prociter_instance(gc_read, 1, &gc_read_ownreqs, &(gc_read_of_int_ops));
        add_parm_info_type(0, char_ops, gc_dump_of_t_reqs);
        find_prociter_instance(gc_dump, 1, &gc_dump_ownreqs, &(gc_dump_of_char_ops));
        add_parm_info_type(0, char_ops, gc_read_of_t_reqs);
        find_prociter_instance(gc_read, 1, &gc_read_ownreqs, &(gc_read_of_char_ops));
        add_parm_info_type(0, string_ops, gc_dump_of_t_reqs);
        find_prociter_instance(gc_dump, 1, &gc_dump_ownreqs, &(gc_dump_of_string_ops));
        add_parm_info_type(0, string_ops, gc_read_of_t_reqs);
        find_prociter_instance(gc_read, 1, &gc_read_ownreqs, &(gc_read_of_string_ops));
        add_parm_info_type(0, int_ops, array_of_t_reqs);
        find_type_instance(array_ops, 1, &array_ownreqs, &(array_of_int_ops));
        add_parm_info_type(0, array_of_int_ops, gc_dump_of_t_reqs);
        find_prociter_instance(gc_dump, 1, &gc_dump_ownreqs, &(gc_dump_of_array_of_int_ops));
        add_parm_info_type(0, array_of_int_ops, gc_read_of_t_reqs);
        find_prociter_instance(gc_read, 1, &gc_read_ownreqs, &(gc_read_of_array_of_int_ops));
        add_parm_info_type(0, string_ops, array_of_t_reqs);
        find_type_instance(array_ops, 1, &array_ownreqs, &(array_of_string_ops));
        add_parm_info_type(0, array_of_string_ops, gc_dump_of_t_reqs);
        find_prociter_instance(gc_dump, 1, &gc_dump_ownreqs, &(gc_dump_of_array_of_string_ops));
        add_parm_info_type(0, array_of_string_ops, gc_read_of_t_reqs);
        find_prociter_instance(gc_read, 1, &gc_read_ownreqs, &(gc_read_of_array_of_string_ops));
        stringOPcons("", CLU_1, CLU_0, &STR_);
        stringOPcons("INTEGER (expected result 5)", CLU_1, CLU_27, &STR_INTEGER_040_050expected_040result_0405_051);
        stringOPcons("/tmp/", CLU_1, CLU_5, &STR__057tmp_057);
        stringOPcons("testint", CLU_1, CLU_7, &STR_testint);
        stringOPcons("lib", CLU_1, CLU_3, &STR_lib);
        stringOPcons("Result: ", CLU_1, CLU_8, &STR_Result_072_040);
        stringOPcons("gc_read signals not_possible: ", CLU_1, CLU_30, &STR_gc_137read_040signals_040not_137possible_072_040);
        stringOPcons("CHAR (expected result \'@\')", CLU_1, CLU_26, &STR_CHAR_040_050expected_040result_040_047_100_047_051);
        stringOPcons("testchar", CLU_1, CLU_8, &STR_testchar);
        stringOPcons("Result: \'", CLU_1, CLU_9, &STR_Result_072_040_047);
        stringOPcons("\', ", CLU_1, CLU_3, &STR__047_054_040);
        stringOPcons("STRING (expected result \'abc\')", CLU_1, CLU_30, &STR_STRING_040_050expected_040result_040_047abc_047_051);
        stringOPcons("teststring1", CLU_1, CLU_11, &STR_teststring1);
        stringOPcons("abc", CLU_1, CLU_3, &STR_abc);
        stringOPcons("\'", CLU_1, CLU_1, &STR__047);
        stringOPcons("STRING (expected result \'abcdefghij\')", CLU_1, CLU_37, &STR_STRING_040_050expected_040result_040_047abcdefghij_047_051);
        stringOPcons("teststring2", CLU_1, CLU_11, &STR_teststring2);
        stringOPcons("abcdefghij", CLU_1, CLU_10, &STR_abcdefghij);
        stringOPcons("ARRAY[INT] (expected result 0, 1, 2, 3, 5)", CLU_1, CLU_42, &STR_ARRAY_133INT_135_040_050expected_040result_0400_054_0401_054_0402_054_0403_054_0405_051);
        stringOPcons("testarrayofints", CLU_1, CLU_15, &STR_testarrayofints);
        stringOPcons("Result", CLU_1, CLU_6, &STR_Result);
        stringOPcons("ARRAY[STRING] (expecting to get asdf0, asdf1", CLU_1, CLU_44, &STR_ARRAY_133STRING_135_040_050expecting_040to_040get_040asdf0_054_040asdf1);
        stringOPcons("testarrayofstrings", CLU_1, CLU_18, &STR_testarrayofstrings);
        stringOPcons("asdf0", CLU_1, CLU_5, &STR_asdf0);
        stringOPcons("asdf1", CLU_1, CLU_5, &STR_asdf1);
        start_up_own_init = 1;
    }
    enter_proc(7);

  LINE(9);
    {
    err = logit(STR_);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(10);
    {
    err = logit(STR_INTEGER_040_050expected_040result_0405_051);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(11);
    {
        {CLUREF T_1_1;
        err = file_nameOPcreate(STR__057tmp_057, STR_testint, STR_lib, STR_, &T_1_1);
        if (err != ERR_ok) goto ex_0;
        fn.num = T_1_1.num;
        }
        }

  LINE(12);
    {
        {j.num = 5;
        }
        }

  LINE(13);
    {
    CLUREF T_1_1;
    generic_CLU_proc.type_owns = 0;
    generic_CLU_proc.op_owns = (long)gc_dump_of_int_ops->op_owns;
    generic_CLU_proc.proc = gc_dump;
    CUR_PROC_VAR.proc = &generic_CLU_proc;
    err = gc_dump(j, fn, &T_1_1);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(14);
    {
    CLUREF T_2_1;
    CLUREF T_2_2;
    CLUREF T_2_3;
    generic_CLU_proc.type_owns = 0;
    generic_CLU_proc.op_owns = (long)gc_read_of_int_ops->op_owns;
    generic_CLU_proc.proc = gc_read;
    CUR_PROC_VAR.proc = &generic_CLU_proc;
    err = gc_read(fn, &T_2_1);
    if (err != ERR_ok) goto ex_1;
    err = intOPunparse(T_2_1, &T_2_2);
    if (err != ERR_ok) goto ex_1;
    err = stringOPconcat(STR_Result_072_040, T_2_2, &T_2_3);
    if (err != ERR_ok) goto ex_1;
    err = logit(T_2_3);
    if (err != ERR_ok) goto ex_1;
    }
        goto end_1;
        ex_1:
            if ((err == ERR_not_possible)) {
            CLUREF why;
            why.num = elist[0].num;

  LINE(16);
                {
                CLUREF T_2_1;
                err = stringOPconcat(STR_gc_137read_040signals_040not_137possible_072_040, why, &T_2_1);
                if (err != ERR_ok) goto ex_0;
                err = logit(T_2_1);
                if (err != ERR_ok) goto ex_0;
                }
            }
            else {
                goto ex_0;
            }
        end_1:;

  LINE(19);
    {
    err = logit(STR_);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(20);
    {
    err = logit(STR_CHAR_040_050expected_040result_040_047_100_047_051);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(21);
    {
    CLUREF T_1_1;
    err = file_nameOPcreate(STR__057tmp_057, STR_testchar, STR_lib, STR_, &T_1_1);
    if (err != ERR_ok) goto ex_0;
    fn.num = T_1_1.num;
    }

  LINE(22);
    {
        {CLUREF T_1_1;
        T_1_1.ch = '@';
        c.num = T_1_1.num;
        }
        }

  LINE(23);
    {
    CLUREF T_1_1;
    generic_CLU_proc.type_owns = 0;
    generic_CLU_proc.op_owns = (long)gc_dump_of_char_ops->op_owns;
    generic_CLU_proc.proc = gc_dump;
    CUR_PROC_VAR.proc = &generic_CLU_proc;
    err = gc_dump(c, fn, &T_1_1);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(24);
    {
        {CLUREF T_1_1;
        generic_CLU_proc.type_owns = 0;
        generic_CLU_proc.op_owns = (long)gc_read_of_char_ops->op_owns;
        generic_CLU_proc.proc = gc_read;
        CUR_PROC_VAR.proc = &generic_CLU_proc;
        err = gc_read(fn, &T_1_1);
        if (err != ERR_ok) goto ex_0;
        c2.num = T_1_1.num;
        }
        }

  LINE(25);
    {
    CLUREF T_2_1;
    CLUREF T_2_2;
    CLUREF T_2_3;
    CLUREF T_2_4;
    CLUREF T_2_5;
    CLUREF T_2_6;
    err = stringOPc2s(c2, &T_2_1);
    if (err != ERR_ok) goto ex_2;
    err = stringOPconcat(STR_Result_072_040_047, T_2_1, &T_2_2);
    if (err != ERR_ok) goto ex_2;
    err = stringOPconcat(T_2_2, STR__047_054_040, &T_2_3);
    if (err != ERR_ok) goto ex_2;
    T_2_4.num = (long)(c2.ch & 0xff);
    err = intOPunparse(T_2_4, &T_2_5);
    if (err != ERR_ok) goto ex_2;
    err = stringOPconcat(T_2_3, T_2_5, &T_2_6);
    if (err != ERR_ok) goto ex_2;
    err = logit(T_2_6);
    if (err != ERR_ok) goto ex_2;
    }
        goto end_2;
        ex_2:
            if ((err == ERR_not_possible)) {
            CLUREF why;
            why.num = elist[0].num;

  LINE(27);
                {
                CLUREF T_2_1;
                err = stringOPconcat(STR_gc_137read_040signals_040not_137possible_072_040, why, &T_2_1);
                if (err != ERR_ok) goto ex_0;
                err = logit(T_2_1);
                if (err != ERR_ok) goto ex_0;
                }
            }
            else {
                goto ex_0;
            }
        end_2:;

  LINE(30);
    {
    err = logit(STR_);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(31);
    {
    err = logit(STR_STRING_040_050expected_040result_040_047abc_047_051);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(32);
    {
    CLUREF T_1_1;
    err = file_nameOPcreate(STR__057tmp_057, STR_teststring1, STR_lib, STR_, &T_1_1);
    if (err != ERR_ok) goto ex_0;
    fn.num = T_1_1.num;
    }

  LINE(33);
    {
        {s = STR_abc;
        }
        }

  LINE(34);
    {
    CLUREF T_1_1;
    generic_CLU_proc.type_owns = 0;
    generic_CLU_proc.op_owns = (long)gc_dump_of_string_ops->op_owns;
    generic_CLU_proc.proc = gc_dump;
    CUR_PROC_VAR.proc = &generic_CLU_proc;
    err = gc_dump(s, fn, &T_1_1);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(35);
    {
    CLUREF T_2_1;
    CLUREF T_2_2;
    CLUREF T_2_3;
    generic_CLU_proc.type_owns = 0;
    generic_CLU_proc.op_owns = (long)gc_read_of_string_ops->op_owns;
    generic_CLU_proc.proc = gc_read;
    CUR_PROC_VAR.proc = &generic_CLU_proc;
    err = gc_read(fn, &T_2_1);
    if (err != ERR_ok) goto ex_3;
    err = stringOPconcat(STR_Result_072_040_047, T_2_1, &T_2_2);
    if (err != ERR_ok) goto ex_3;
    err = stringOPconcat(T_2_2, STR__047, &T_2_3);
    if (err != ERR_ok) goto ex_3;
    err = logit(T_2_3);
    if (err != ERR_ok) goto ex_3;
    }
        goto end_3;
        ex_3:
            if ((err == ERR_not_possible)) {
            CLUREF why;
            why.num = elist[0].num;

  LINE(37);
                {
                CLUREF T_2_1;
                err = stringOPconcat(STR_gc_137read_040signals_040not_137possible_072_040, why, &T_2_1);
                if (err != ERR_ok) goto ex_0;
                err = logit(T_2_1);
                if (err != ERR_ok) goto ex_0;
                }
            }
            else {
                goto ex_0;
            }
        end_3:;

  LINE(40);
    {
    err = logit(STR_);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(41);
    {
    err = logit(STR_STRING_040_050expected_040result_040_047abcdefghij_047_051);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(42);
    {
    CLUREF T_1_1;
    err = file_nameOPcreate(STR__057tmp_057, STR_teststring2, STR_lib, STR_, &T_1_1);
    if (err != ERR_ok) goto ex_0;
    fn.num = T_1_1.num;
    }

  LINE(43);
    {
    s = STR_abcdefghij;
    }

  LINE(44);
    {
    CLUREF T_1_1;
    generic_CLU_proc.type_owns = 0;
    generic_CLU_proc.op_owns = (long)gc_dump_of_string_ops->op_owns;
    generic_CLU_proc.proc = gc_dump;
    CUR_PROC_VAR.proc = &generic_CLU_proc;
    err = gc_dump(s, fn, &T_1_1);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(45);
    {
    CLUREF T_2_1;
    CLUREF T_2_2;
    CLUREF T_2_3;
    generic_CLU_proc.type_owns = 0;
    generic_CLU_proc.op_owns = (long)gc_read_of_string_ops->op_owns;
    generic_CLU_proc.proc = gc_read;
    CUR_PROC_VAR.proc = &generic_CLU_proc;
    err = gc_read(fn, &T_2_1);
    if (err != ERR_ok) goto ex_4;
    err = stringOPconcat(STR_Result_072_040_047, T_2_1, &T_2_2);
    if (err != ERR_ok) goto ex_4;
    err = stringOPconcat(T_2_2, STR__047, &T_2_3);
    if (err != ERR_ok) goto ex_4;
    err = logit(T_2_3);
    if (err != ERR_ok) goto ex_4;
    }
        goto end_4;
        ex_4:
            if ((err == ERR_not_possible)) {
            CLUREF why;
            why.num = elist[0].num;

  LINE(47);
                {
                CLUREF T_2_1;
                err = stringOPconcat(STR_gc_137read_040signals_040not_137possible_072_040, why, &T_2_1);
                if (err != ERR_ok) goto ex_0;
                err = logit(T_2_1);
                if (err != ERR_ok) goto ex_0;
                }
            }
            else {
                goto ex_0;
            }
        end_4:;

  LINE(50);
    {
    err = logit(STR_);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(51);
    {
    err = logit(STR_ARRAY_133INT_135_040_050expected_040result_0400_054_0401_054_0402_054_0403_054_0405_051);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(52);
    {
    CLUREF T_1_1;
    err = file_nameOPcreate(STR__057tmp_057, STR_testarrayofints, STR_lib, STR_, &T_1_1);
    if (err != ERR_ok) goto ex_0;
    fn.num = T_1_1.num;
    }

  LINE(53);
    {
        {CLUREF T_1_1;
        err = arrayOPnew( &T_1_1);
        if (err != ERR_ok) goto ex_0;
        ai.num = T_1_1.num;
        }
        }

  LINE(54);
    {
    {
    if ((ai.array->int_low + ai.array->ext_size + 1) < ai.array->int_size) {
        ai.array->store->data[ai.array->int_low + ai.array->ext_size] = 0;
        ai.array->ext_size++; ai.array->ext_high++;}
    else {
        err = arrayOPaddh(ai, CLU_0);
        if (err != ERR_ok) goto ex_0;}
    }
    }

  LINE(55);
    {
    {
    if ((ai.array->int_low + ai.array->ext_size + 1) < ai.array->int_size) {
        ai.array->store->data[ai.array->int_low + ai.array->ext_size] = 1;
        ai.array->ext_size++; ai.array->ext_high++;}
    else {
        err = arrayOPaddh(ai, CLU_1);
        if (err != ERR_ok) goto ex_0;}
    }
    }

  LINE(56);
    {
    {
    if ((ai.array->int_low + ai.array->ext_size + 1) < ai.array->int_size) {
        ai.array->store->data[ai.array->int_low + ai.array->ext_size] = 2;
        ai.array->ext_size++; ai.array->ext_high++;}
    else {
        err = arrayOPaddh(ai, CLU_2);
        if (err != ERR_ok) goto ex_0;}
    }
    }

  LINE(57);
    {
    {
    if ((ai.array->int_low + ai.array->ext_size + 1) < ai.array->int_size) {
        ai.array->store->data[ai.array->int_low + ai.array->ext_size] = 3;
        ai.array->ext_size++; ai.array->ext_high++;}
    else {
        err = arrayOPaddh(ai, CLU_3);
        if (err != ERR_ok) goto ex_0;}
    }
    }

  LINE(58);
    {
    {
    if ((ai.array->int_low + ai.array->ext_size + 1) < ai.array->int_size) {
        ai.array->store->data[ai.array->int_low + ai.array->ext_size] = 4;
        ai.array->ext_size++; ai.array->ext_high++;}
    else {
        err = arrayOPaddh(ai, CLU_4);
        if (err != ERR_ok) goto ex_0;}
    }
    }

  LINE(59);
    {
    CLUREF T_1_1;
    generic_CLU_proc.type_owns = 0;
    generic_CLU_proc.op_owns = (long)gc_dump_of_array_of_int_ops->op_owns;
    generic_CLU_proc.proc = gc_dump;
    CUR_PROC_VAR.proc = &generic_CLU_proc;
    err = gc_dump(ai, fn, &T_1_1);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(60);
    {
        {CLUREF T_2_1;
        generic_CLU_proc.type_owns = 0;
        generic_CLU_proc.op_owns = (long)gc_read_of_array_of_int_ops->op_owns;
        generic_CLU_proc.proc = gc_read;
        CUR_PROC_VAR.proc = &generic_CLU_proc;
        err = gc_read(fn, &T_2_1);
        if (err != ERR_ok) goto ex_5;
        aix.num = T_2_1.num;
        }
        }
        goto end_5;
        ex_5:
            if ((err == ERR_not_possible)) {
            CLUREF why;
            why.num = elist[0].num;

  LINE(62);
                {
                CLUREF T_2_1;
                err = stringOPconcat(STR_gc_137read_040signals_040not_137possible_072_040, why, &T_2_1);
                if (err != ERR_ok) goto ex_0;
                err = logit(T_2_1);
                if (err != ERR_ok) goto ex_0;
                }
            }
            else {
                goto ex_0;
            }
        end_5:;

  LINE(64);
    {
    err = logit(STR_Result);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(65);
    {
    CLUREF T_1_1;
    CLUREF T_1_2;
    CLUREF T_1_3;
        T_1_2.num = aix.array->ext_high; 
        T_1_3 = aix;
        for (T_1_1.num = aix.array->ext_low; T_1_1.num <= T_1_2.num; T_1_1.num++) {
            if (T_1_1.num > T_1_3.array->ext_high || T_1_1.num < T_1_3.array->ext_low) {
                err = ERR_failure;
                elist[0].str = array_bounds_exception_STRING;
                goto ex_0;}
            i1.num = T_1_3.array->store->data[T_1_1.num - T_1_3.array->ext_low + T_1_3.array->int_low];

  LINE(66);
            {
            CLUREF T_2_1;
            err = intOPunparse(i1, &T_2_1);
            if (err != ERR_ok) goto ex_0;
            err = logit(T_2_1);
            if (err != ERR_ok) goto ex_0;
            }
        }
    }
    end_inline_for_1:;

  LINE(69);
    {
    err = logit(STR_);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(70);
    {
    err = logit(STR_ARRAY_133STRING_135_040_050expecting_040to_040get_040asdf0_054_040asdf1);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(71);
    {
    CLUREF T_1_1;
    err = file_nameOPcreate(STR__057tmp_057, STR_testarrayofstrings, STR_lib, STR_, &T_1_1);
    if (err != ERR_ok) goto ex_0;
    fn.num = T_1_1.num;
    }

  LINE(72);
    {
        {CLUREF T_1_1;
        err = arrayOPnew( &T_1_1);
        if (err != ERR_ok) goto ex_0;
        a.num = T_1_1.num;
        }
        }

  LINE(73);
    {
    {
    if ((a.array->int_low + a.array->ext_size + 1) < a.array->int_size) {
        a.array->store->data[a.array->int_low + a.array->ext_size] = STR_asdf0.num;
        a.array->ext_size++; a.array->ext_high++;}
    else {
        err = arrayOPaddh(a, STR_asdf0);
        if (err != ERR_ok) goto ex_0;}
    }
    }

  LINE(74);
    {
    {
    if ((a.array->int_low + a.array->ext_size + 1) < a.array->int_size) {
        a.array->store->data[a.array->int_low + a.array->ext_size] = STR_asdf1.num;
        a.array->ext_size++; a.array->ext_high++;}
    else {
        err = arrayOPaddh(a, STR_asdf1);
        if (err != ERR_ok) goto ex_0;}
    }
    }

  LINE(78);
    {
    CLUREF T_1_1;
    generic_CLU_proc.type_owns = 0;
    generic_CLU_proc.op_owns = (long)gc_dump_of_array_of_string_ops->op_owns;
    generic_CLU_proc.proc = gc_dump;
    CUR_PROC_VAR.proc = &generic_CLU_proc;
    err = gc_dump(a, fn, &T_1_1);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(79);
    {
        {CLUREF T_2_1;
        generic_CLU_proc.type_owns = 0;
        generic_CLU_proc.op_owns = (long)gc_read_of_array_of_string_ops->op_owns;
        generic_CLU_proc.proc = gc_read;
        CUR_PROC_VAR.proc = &generic_CLU_proc;
        err = gc_read(fn, &T_2_1);
        if (err != ERR_ok) goto ex_6;
        ax.num = T_2_1.num;
        }
        }
        goto end_6;
        ex_6:
            if ((err == ERR_not_possible)) {
            CLUREF why;
            why.num = elist[0].num;

  LINE(81);
                {
                CLUREF T_2_1;
                err = stringOPconcat(STR_gc_137read_040signals_040not_137possible_072_040, why, &T_2_1);
                if (err != ERR_ok) goto ex_0;
                err = logit(T_2_1);
                if (err != ERR_ok) goto ex_0;
                }
            }
            else {
                goto ex_0;
            }
        end_6:;

  LINE(83);
    {
    err = logit(STR_Result);
    if (err != ERR_ok) goto ex_0;
    }

  LINE(84);
    {
    CLUREF T_1_1;
    CLUREF T_1_2;
    CLUREF T_1_3;
        T_1_2.num = ax.array->ext_high; 
        T_1_3 = ax;
        for (T_1_1.num = ax.array->ext_low; T_1_1.num <= T_1_2.num; T_1_1.num++) {
            if (T_1_1.num > T_1_3.array->ext_high || T_1_1.num < T_1_3.array->ext_low) {
                err = ERR_failure;
                elist[0].str = array_bounds_exception_STRING;
                goto ex_0;}
            s1.num = T_1_3.array->store->data[T_1_1.num - T_1_3.array->ext_low + T_1_3.array->int_low];

  LINE(85);
            {
            err = logit(s1);
            if (err != ERR_ok) goto ex_0;
            }
        }
    }
    end_inline_for_2:;
    goto end_0;
    ex_0:
        {
            if (err == ERR_failure) {signal(ERR_failure);}
            elist[0] = _pclu_erstr(err);
            {signal(ERR_failure);}
        }
    end_0: {signal(ERR_ok);}
    }

/**** END PROCEDURE start_up ****/

